### ISSUE TITLE
give Leon latlong for upper left,bottom right

### ISSUE THREAD

**Issue by fsxfreak** [fsxfreak/harpyie-vision#6]
Give me them by Monday at 8:00pm.

**Comment by bk752** [comment]
Upper Left  ( -88.7126917,  16.5637965) ( 88d42'45.69"W, 16d33'49.67"N)
Lower Left  ( -88.7126917,  16.5290313) ( 88d42'45.69"W, 16d31'44.51"N)
Upper Right ( -88.6792337,  16.5637965) ( 88d40'45.24"W, 16d33'49.67"N)
Lower Right ( -88.6792337,  16.5290313) ( 88d40'45.24"W, 16d31'44.51"N)
Center      ( -88.6959627,  16.5464139) ( 88d41'45.47"W, 16d32'47.09"N)

**Comment by fsxfreak** [comment]
upper left (lat, lon) (16.5637965, -88.7126917)
bottom right (lat, lon) (16.5290313, -88.6792337)
